services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: finance-manager-password-123
      POSTGRES_USER: finance-manager-user
      POSTGRES_DB: finance-manager-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
