spring.application.name=finance-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/finance-manager-db
spring.datasource.username=finance-manager-user
spring.datasource.password=finance-manager-password-123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.port=8080